name: Azure Financial Data Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  run-data-pipeline:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Extract Script (API → Bronze)
      working-directory: scripts
      env:
        STOCK_API_KEY: ${{ secrets.STOCK_API_KEY }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: python extract_massive_data.py

    - name: Run Transform Script (Bronze → Silver)
      working-directory: scripts
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: python bronze_to_silver.py

    - name: Run Silver to Gold
      working-directory: scripts
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: python silver_to_gold.py
